name: Deploy with gh-pages

on: [push]

jobs:
  deploy-gh-pages:
    name: "setup - gh-pages"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy